package com.zitga.idle.enumeration.resource;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public enum ResourceSource {

    PLAYER_NAME_CHANGE(10),

    PREMIUM_MAIL_REWARD(15),

    HERO_LEVEL_UP(20),
    HERO_EVOLVE(21),
    HERO_ADD(22),

    ALTAR_HERO_DISASSEMBLE(30),
    ALTAR_HERO_RESET(33),

    SUMMON_HERO_BASIC_SCROLL(40),
    SUMMON_HERO_PREMIUM_SCROLL(41),
    SUMMON_HERO_FRIEND_POINT(42),
    SUMMON_HERO_ACCUMULATE_POINT(43),
    SUMMON_HERO_BY_FRAGMENT(44),
    SUMMON_HERO_EVENT_RATE_UP(45),

    PROPHET_TREE_SUMMON(50),
    PROPHET_TREE_CONVERT(51),

    EQUIPMENT_UPGRADE_ON_BLACKSMITH(60),
    EQUIPMENT_UPGRADE_ON_HERO(61),
    EQUIPMENT_SELL(62),

    ARTIFACT_COMBINE(70),
    ARTIFACT_UPGRADE(71),

    STONE_CONVERT(80),
    STONE_UPGRADE(81),
    STONE_UNLOCK(82),

    TALENT_REFRESH(85),
    TALENT_RESET(86),

    CASINO_SPIN_BASIC(90),
    CASINO_SPIN_PREMIUM(91),
    CASINO_REFRESH(92),
    CASINO_CHIP_BUY(93),

    CAMPAIGN_ITEM_CLAIM(100),
    CAMPAIGN_RESOURCE_CLAIM(102),
    CAMPAIGN_CHALLENGE(103),
    CAMPAIGN_QUICK_BATTLE(104),
    CAMPAIGN_QUICK_BATTLE_TICKET_USE(105),

    DAILY_REWARD_CLAIM(110),

    VIDEO_REWARD_CLAIM(120),

    TOWER_CHALLENGE(130),
    TOWER_STAMINA_BUY(131),

    HAND_OF_MIDAS_CLAIM(140),

    RAID_CHALLENGE(150),
    RAID_STAMINA_BUY(151),

    SUMMONER_LEVEL_UP(160),

    DUNGEON_SMASH(170),
    DUNGEON_CHALLENGE(171),
    DUNGEON_SHOP_BUY(173),

    MASTERY_UPGRADE(180),
    MASTERY_RESET(181),

    SUMMONER_EVOLVE(190),

    TAVERN_QUEST_REROLL(201),
    TAVERN_QUEST_ADD(202),
    TAVERN_QUEST_SPEED_UP(203),
    TAVERN_QUEST_COMPLETE(204),

    MARKET_REFRESH(220),
    ALTAR_MARKET_REFRESH(221),
    ARENA_MARKET_REFRESH(222),
    GUILD_MARKET_REFRESH(223),
    EVENT_MARKET_REFRESH(224),

    MARKET_BUY(230),
    ALTAR_MARKET_BUY(231),
    ARENA_MARKET_BUY(232),
    GUILD_MARKET_BUY(233),
    EVENT_MARKET_BUY(234),
    ARENA_TEAM_MARKET_BUY(235),

    VIP_LEVEL_UP(240),

    SKIN_COMBINE(250),
    SKIN_BUNDLE_PURCHASE(251),
    SKIN_BUNDLE_PURCHASE_FREE(252),
    SKIN_EXCHANGE(253),

    FRIEND_POINT_CLAIM(260),

    MARKET_UPGRADE(270),
    ALTAR_MARKET_UPGRADE(271),
    ARENA_MARKET_UPGRADE(272),
    GUILD_MARKET_UPGRADE(273),
    EVENT_MARKET_UPGRADE(274),
    ARENA_TEAM_MARKET_UPGRADE(275),

    DEFENSE_CHALLENGE(280),
    DEFENSE_IDLE_CLAIM(281),

    ARENA_CHALLENGE(290),
    ARENA_TICKET_BUY(292),
    ARENA_SEASON_REWARD_CLAIM(293),
    ARENA_CHEST_OPEN(294),

    ARENA_TEAM_CHALLENGE(295),
    ARENA_TEAM_TICKET_BUY(296),
    ARENA_TEAM_SEASON_REWARD_CLAIM(297),

    TUTORIAL_SUMMON_HERO(300),
    TUTORIAL_MARKET_BUY(301),

    QUEST_DAILY_CLAIM(310),
    QUEST_ACHIEVEMENT_CLAIM(311),
    QUEST_TREE_CLAIM(312),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    PURCHASE_RAW_PACK(420),
    PURCHASE_SUBSCRIPTION_PACK(421),
    PURCHASE_SUBSCRIPTION_PACK_DAILY_REWARD(422),
    PURCHASE_LIMITED_PACK(424),
    PURCHASE_SUBSCRIPTION_TRIAL_PACK_DAILY_REWARD(425),
    PURCHASE_CUSTOMIZE_BUNDLE_PACK(426),
    PURCHASE_CUSTOMIZE_BUNDLE_PACK_FREE(427),
    PURCHASE_GROWTH_PACK(428),
    PURCHASE_PROGRESS_PACK(429),

    GIFT_CODE_CLAIM(430),

    PURCHASE_RAW_PACK_FREE(440),
    PURCHASE_SUBSCRIPTION_PACK_FREE(441),
    PURCHASE_LIMITED_PACK_FREE(443),
    PURCHASE_FIRST_TIME_REWARD(445),
    PURCHASE_GROWTH_PACK_FREE(447),
    PURCHASE_PROGRESS_PACK_FREE(448),

    GROWTH_PACK_MILESTONE_CLAIM(490),

    GUILD_CREATE(500),

    GUILD_CHECK_IN(510),

    GUILD_BOSS_CHALLENGE(530),
    GUILD_BOSS_DAILY_REWARD_CLAIM(531),
    GUILD_BOSS_MONTHLY_REWARD_CLAIM(532),

    GUILD_DUNGEON_CHALLENGE(540),
    GUILD_DUNGEON_TRAINING_CHALLENGE(541),
    GUILD_DUNGEON_SEASON_REWARD_CLAIM(542),
    GUILD_DUNGEON_STAGE_REWARD_CLAIM(543),

    GUILD_WAR_BATTLE_REWARD_CLAIM(550),
    GUILD_WAR_SEASON_REWARD_CLAIM(551),
    GUILD_WAR_CHALLENGE(552),

    RAISE_SLOT_RESET(560),
    RAISE_SLOT_UNLOCK(561),
    RAISE_HERO_IDLE_CLAIM(562),
    RAISE_HERO_QUICK_BATTLE_CLAIM(563),

    REGRESS_HERO(570),

    COMEBACK_DAILY_LOGIN_CLAIM(580),
    COMEBACK_DAILY_QUEST_REWARD(581),
    COMEBACK_BUNDLE_PURCHASE_FREE(582),
    COMEBACK_BUNDLE_PURCHASE(583),

    DOMAINS_CHALLENGE_REWARD(590),
    DOMAINS_CHALLENGE(591),
    DOMAINS_CHEST_OPEN(592),


    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_BUNDLE_PURCHASE_PACK(600),
    EVENT_BUNDLE_PURCHASE_PACK_FREE(601),

    EVENT_SUMMON_QUEST_CLAIM(610),

    EVENT_ARENA_QUEST_CLAIM(620),

    EVENT_TAVERN_QUEST_CLAIM(630),

    EVENT_PROPHET_TREE_QUEST_CLAIM(640),

    EVENT_CASINO_QUEST_CLAIM(650),

    EVENT_HERO_COLLECT_QUEST_CLAIM(660),

    EVENT_LOGIN_CLAIM(670),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_HOT_DEAL_PURCHASE_PACK(680),
    EVENT_HOT_DEAL_PURCHASE_PACK_FREE(681),

    EVENT_RELEASE_FESTIVAL_CLAIM(690),

    EVENT_EXCHANGE_SPEND(700),
    EVENT_EXCHANGE_CLAIM(701),

    EVENT_ARENA_RANK_CLAIM(710),

    EVENT_SPIN_QUEST_CLAIM(720),

    EVENT_GUILD_QUEST_ACTIVITY(730),
    EVENT_GUILD_QUEST_REWARD(731),
    EVENT_GUILD_QUEST_DONATE(732),

    EVENT_SERVER_OPEN_BUY(740),
    EVENT_SERVER_OPEN_PROGRESS_CLAIM(741),
    EVENT_SERVER_OPEN_QUEST_CLAIM(742),

    EVENT_SERVER_OPEN_ARENA_RANKING_REWARD(745),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_MID_AUTUMN_PURCHASE_PACK(750),
    EVENT_MID_AUTUMN_PURCHASE_FREE_PACK(751),
    EVENT_MID_AUTUMN_LOGIN_CLAIM(752),
    EVENT_MID_AUTUMN_EXCHANGE_SPEND(753),
    EVENT_MID_AUTUMN_EXCHANGE_CLAIM(754),
    EVENT_MID_AUTUMN_GEM_BOX_SPEND(755),
    EVENT_MID_AUTUMN_GEM_BOX_CLAIM(756),
    EVENT_MID_AUTUMN_FEED_BEAST(757),
    EVENT_MID_AUTUMN_FEED_BEAST_QUEST_CLAIM(758),
    EVENT_MID_AUTUMN_GOLDEN_TIME_IDLE(759),
    EVENT_MID_AUTUMN_GOLDEN_TIME_QUICK_BATTLE(760),
    EVENT_MID_AUTUMN_FEED_BEAST_CLAIM(761),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_ARENA_PASS_MILESTONE_CLAIM(770),
    EVENT_ARENA_PASS_PURCHASE_PACK(771),
    EVENT_ARENA_PASS_PURCHASE_PACK_FREE(772),
    EVENT_ARENA_PASS_CHALLENGE_BONUS(773),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_DAILY_QUEST_PASS_MILESTONE_CLAIM(780),
    EVENT_DAILY_QUEST_PASS_PURCHASE_PACK(781),
    EVENT_DAILY_QUEST_PASS_PURCHASE_PACK_FREE(782),
    EVENT_DAILY_QUEST_PASS_BONUS(783),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_HALLOWEEN_IDLE(790),
    EVENT_HALLOWEEN_QUICK_BATTLE(791),
    EVENT_HALLOWEEN_BUNDLE_PURCHASE_PACK_FREE(792),
    EVENT_HALLOWEEN_BUNDLE_PURCHASE_PACK(793),
    EVENT_HALLOWEEN_LOGIN_CLAIM(794),
    EVENT_HALLOWEEN_EXCHANGE(796),
    EVENT_HALLOWEEN_EXCHANGE_CLAIM(797),
    EVENT_HALLOWEEN_DAILY_PURCHASE_PACK_FREE(798),
    EVENT_HALLOWEEN_DAILY_PURCHASE_PACK(799),
    EVENT_HALLOWEEN_DICE_ROLL(800),
    EVENT_HALLOWEEN_DICE_ROLL_REWARD(801),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_BLACK_FRIDAY_GEM_PACK_BUY(810),
    EVENT_BLACK_FRIDAY_GEM_PACK_REWARD(811),
    EVENT_BLACK_FRIDAY_CARD_PURCHASE_FREE(812),
    EVENT_BLACK_FRIDAY_CARD_PURCHASE(813),
    EVENT_BLACK_FRIDAY_CARD_DAILY_REWARD(814),
    EVENT_BLACK_FRIDAY_LOGIN_DAILY_REWARD(815),
    EVENT_BLACK_FRIDAY_BUNDLE_PURCHASE_PACK_FREE(816),
    EVENT_BLACK_FRIDAY_BUNDLE_PURCHASE_PACK(817),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_CHRISTMAS_LOGIN_CLAIM_REWARD(821),
    EVENT_CHRISTMAS_IDLE_CLAIM(822),
    EVENT_CHRISTMAS_QUICK_BATTLE(823),
    EVENT_CHRISTMAS_BOX_OPEN(824),
    EVENT_CHRISTMAS_DAILY_PURCHASE_PACK_FREE(826),
    EVENT_CHRISTMAS_DAILY_PURCHASE_PACK(827),
    EVENT_CHRISTMAS_OFFER_PURCHASE_PACK_FREE(828),
    EVENT_CHRISTMAS_OFFER_PURCHASE_PACK(829),
    EVENT_CHRISTMAS_EXCHANGE(830),
    EVENT_CHRISTMAS_CHALLENGE_BOSS(832),

    EVENT_SALE_OFF_PURCHASE_PACK(890),
    EVENT_SALE_OFF_PURCHASE_PACK_FREE(891),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_NEW_YEAR_BOX_SPEND(840),
    EVENT_NEW_YEAR_BOX_CLAIM(841),
    EVENT_NEW_YEAR_DAILY_PURCHASE_PACK_FREE(842),
    EVENT_NEW_YEAR_DAILY_PURCHASE_PACK(843),
    EVENT_NEW_YEAR_CARD_PURCHASE_FREE(844),
    EVENT_NEW_YEAR_CARD_PURCHASE(845),
    EVENT_NEW_YEAR_CARD_DAILY_REWARD(846),
    EVENT_NEW_YEAR_IDLE(847),
    EVENT_NEW_YEAR_QUICK_BATTLE(848),
    EVENT_NEW_YEAR_LOTTERY_ROLL(849),
    EVENT_NEW_YEAR_LOTTERY_ROLL_REWARD(850),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_LUNAR_NEW_YEAR_LOGIN_CLAIM_REWARD(861),
    EVENT_LUNAR_NEW_YEAR_IDLE(862),
    EVENT_LUNAR_NEW_YEAR_QUICK_BATTLE(863),
    EVENT_LUNAR_NEW_YEAR_DICE_ROLL(864),
    EVENT_LUNAR_NEW_YEAR_DAILY_QUEST_CLAIM(866),
    EVENT_LUNAR_NEW_YEAR_LUNAR_SHOP_EXCHANGE(867),
    EVENT_LUNAR_NEW_YEAR_CHALLENGE_BOSS(869),
    EVENT_LUNAR_NEW_YEAR_CLEAR_BOSS_REWARD(871),
    EVENT_LUNAR_NEW_YEAR_LUNAR_BUNDLE_PURCHASE_PACK_FREE(873),
    EVENT_LUNAR_NEW_YEAR_LUNAR_BUNDLE_PURCHASE_PACK(874),
    EVENT_LUNAR_NEW_YEAR_ELITE_BUNDLE_PURCHASE_PACK_FREE(875),
    EVENT_LUNAR_NEW_YEAR_ELITE_BUNDLE_PURCHASE_PACK(876),
    EVENT_LUNAR_NEW_YEAR_EXCHANGE(877),
    EVENT_LUNAR_NEW_YEAR_STAGE_PASS_REWARD(879),
    EVENT_LUNAR_NEW_YEAR_ELITE_SUMMON(880),
    EVENT_LUNAR_NEW_YEAR_ELITE_SKIN_BUNDLE_PURCHASE_PACK_FREE(881),
    EVENT_LUNAR_NEW_YEAR_ELITE_SKIN_BUNDLE_PURCHASE_PACK(881),

    // update ResourceTracker.getResourceTrackingState() to track buy event
    EVENT_VALENTINE_LOGIN_CLAIM_REWARD(891),
    EVENT_VALENTINE_CHALLENGE_BOSS(892),
    EVENT_VALENTINE_CHALLENGE_BOSS_REWARD(893),
    EVENT_VALENTINE_STAMINA_BUY(894),
    EVENT_VALENTINE_SKIN_BUNDLE_PACK_FREE(895),
    EVENT_VALENTINE_SKIN_BUNDLE_PACK(896),
    EVENT_VALENTINE_ELITE_BUNDLE_PACK_FREE(897),
    EVENT_VALENTINE_ELITE_BUNDLE_PACK(898),
    EVENT_VALENTINE_LOVE_CHALLENGE_BUNDLE_PACK_FREE(899),
    EVENT_VALENTINE_LOVE_CHALLENGE_BUNDLE_PACK(1010),
    EVENT_VALENTINE_OPEN_CARD(1011),

    EVENT_COMMUNITY_REWARD(1020),

    EVENT_NEW_HERO_LOGIN_CLAIM(1030),
    EVENT_NEW_HERO_EXCHANGE(1031),
    EVENT_NEW_HERO_DAILY_QUEST_CLAIM(1032),
    EVENT_NEW_HERO_SPIN(1034),
    EVENT_NEW_HERO_SUMMON_QUEST_REWARD(1035),
    EVENT_NEW_HERO_BUNDLE_FREE(1036),
    EVENT_NEW_HERO_BUNDLE(1037),
    EVENT_NEW_HERO_SUMMON_COLLECTION_QUEST_CLAIM(1038),
    EVENT_NEW_HERO_SPIN_ROSE_BUY(1039),

    EVENT_SERVER_MERGE_DAILY_QUEST_CLAIM(1040),
    EVENT_SERVER_MERGE_LOGIN_CLAIM(1041),
    EVENT_SERVER_MERGE_EXCHANGE(1042),
    EVENT_SERVER_MERGE_ACCUMULATE_QUEST_CLAIM(1043),
    EVENT_SERVER_MERGE_BUNDLE(1044),

    EVENT_EASTER_LOGIN_CLAIM(1050),
    EVENT_EASTER_CARD_PURCHASE_FREE(1051),
    EVENT_EASTER_CARD_PURCHASE(1052),
    EVENT_EASTER_CARD_DAILY_REWARD(1053),
    EVENT_EASTER_DAILY_BUNDLE_PURCHASE_FREE(1054),
    EVENT_EASTER_DAILY_BUNDLE_PURCHASE(1055),
    EVENT_EASTER_OFFER_PURCHASE_FREE(1056),
    EVENT_EASTER_OFFER_PURCHASE(1057),
    EVENT_EASTER_IDLE_CLAIM(1058),
    EVENT_EASTER_QUICK_BATTLE(1059),
    EVENT_EASTER_EGG_BREAK(1060),
    EVENT_EASTER_EGG_EXCHANGE(1061),
    EVENT_EASTER_EGG_HUNT(1062),
    EVENT_EASTER_DAILY_QUEST_REWARD(1063),

    EVENT_NEW_HERO_CHALLENGE_BOSS(1070),
    EVENT_NEW_HERO_BOSS_RANKING(1071),

    EVENT_NEW_HERO_TREASURE_BUY_REWARD(1072),
    EVENT_NEW_HERO_TREASURE_IDLE_CLAIM(1073),
    EVENT_NEW_HERO_TREASURE_QUICK_BATTLE(1074),

    EVENT_NEW_HERO_TREASURE_ISLAND_UNLOCK(1075),
    EVENT_NEW_HERO_TREASURE_COMPLETED_LINE_REWARD(1076),

    EVENT_NEW_HERO_SKIN_BUNDLE_FREE(1077),
    EVENT_NEW_HERO_SKIN_BUNDLE(1078),

    EVENT_BIRTHDAY_LOGIN_CLAIM(1080),
    EVENT_BIRTHDAY_DAILY_BUNDLE_FREE(1083),
    EVENT_BIRTHDAY_DAILY_BUNDLE(1084),
    EVENT_BIRTHDAY_ANNIVERSARY_OFFER_PURCHASE_FREE(1085),
    EVENT_BIRTHDAY_ANNIVERSARY_OFFER_PURCHASE(1086),
    EVENT_BIRTHDAY_EXCHANGE(1087),
    EVENT_BIRTHDAY_WHEEL_SPIN(1088),
    EVENT_BIRTHDAY_CHALLENGE_REWARD(1089),

    EVENT_SKIN_BUNDLE_FREE(1090),
    EVENT_SKIN_BUNDLE(1091),

    EVENT_NEW_HERO_RELEASE_BUNDLE_FREE(1092),
    EVENT_NEW_HERO_RELEASE_BUNDLE(1093),
    EVENT_HERO_RELEASE_COLLECTION_QUEST_CLAIM(1094),
    EVENT_HERO_RELEASE_RATE_UP(1095),
    EVENT_HERO_RELEASE_DAILY_QUEST_CLAIM(1096),

    EVENT_BATTLE_PASS_BUNDLE(1100),
    EVENT_BATTLE_PASS_LEVEL_BUNDLE(1101),
    EVENT_BATTLE_PASS_LEVEL_REWARD_CLAIM(1102),
    EVENT_BATTLE_PASS_EXCHANGE_EXP(1103),

    EVENT_BATTLE_PASS_QUEST_CLAIM(1105),

    EVENT_NEW_SERVER_OPEN_DAILY_QUEST_CLAIM(1110),
    EVENT_NEW_SERVER_SPIN_REWARD(1111),
    EVENT_NEW_SERVER_OPEN_BUNDLE(1112),
    EVENT_NEW_SERVER_OPEN_BUNDLE_FREE(1113),
    EVENT_NEW_SERVER_OPEN_LOGIN_REWARD(1114),

    EVENT_SERVER_OPEN_2_QUEST_CLAIM(1120),
    EVENT_NEW_SERVER_OPEN_2_BUNDLE(1121),
    EVENT_NEW_SERVER_OPEN_2_BUNDLE_FREE(1122),

    EVENT_SERVER_OPEN_ARENA_2_RANKING_REWARD(1123),

    EVENT_NEW_SERVER_OPEN_3_BUNDLE(1125),
    EVENT_NEW_SERVER_OPEN_3_BUNDLE_FREE(1126),
    EVENT_SERVER_OPEN_3_QUEST_CLAIM(1127),


    EVENT_IDLE_EFFECT_CUSTOMIZE_BUNDLE(1130),
    EVENT_IDLE_EFFECT_CUSTOMIZE_BUNDLE_FREE(1131),
    EVENT_IDLE_EFFECT_RANDOM_BUNDLE(1132),
    EVENT_IDLE_EFFECT_RANDOM_BUNDLE_FREE(1133),

    BUG_COMPENSATION(900),

    BALANCE_COMPENSATION(901),

    EVENT_OUT_GAME_REWARD(902),

    MAINTENANCE_COMPENSATION(903),

    FAKE_DATA(1000),
    ;

    private static final Map<Integer, ResourceSource> sourceMap = new ConcurrentHashMap<>();
    private final int value;

    ResourceSource(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }

    public static ResourceSource toSource(int source) {
        return sourceMap.get(source);
    }

    static {
        ResourceSource[] sources = ResourceSource.values();
        for (ResourceSource source : sources) {
            sourceMap.put(source.getValue(), source);
        }
    }
}